backend:
  name: git-gateway
  branch: main

media_folder: "images"

collections:
  - name: "index"
    label: "index"
    folder: "/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"    
    fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Title", name: "title", widget: "string"}
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Subheading", name: "subheading", widget: "string"}
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Background Image", name: "background_image", widget: "image"}
          - label: "About Section"
            name: "about"
            widget: "object"
            fields:
              - {label: "Subheading", name: "subheading", widget: "string"}
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Content", name: "content", widget: "markdown"}
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - {label: "Service Name", name: "name", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "string"}
          - label: "Team Members"
            name: "team"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Position", name: "position", widget: "string"}
              - {label: "Testimonial", name: "text", widget: "text"}
              - {label: "Image", name: "image", widget: "image"}

  - name: "settings"
    label: "Settings"
    files:
      - label: "Site Info"
        name: "info"
        file: "site_info.json"
        fields:
          - {label: "Site Title", name: "site_title", widget: "string"}
          - {label: "Phone Number", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - label: "Social Media"
            name: "social"
            widget: "object"
            fields:
              - {label: "Facebook URL", name: "facebook", widget: "string"}
              - {label: "TikTok URL", name: "tiktok", widget: "string"}
              - {label: "Instagram URL", name: "instagram", widget: "string"}